👷‍♂️ upates squash action

diff --git a/.github/workflows/enforce-squash-merge.yml b/.github/workflows/enforce-squash-merge.yml
--- a/.github/workflows/enforce-squash-merge.yml
+++ b/.github/workflows/enforce-squash-merge.yml
@@ -4,17 +4,19 @@ on:
   pull_request:
     branches:
       - development
-    types:
-      - closed
 
 jobs:
   enforce-squash:
-    if: github.event.pull_request.merged == true
     runs-on: ubuntu-latest
 
     steps:
       - name: Check Merge Method
         run: |
+          if [[ "${{ github.event.pull_request.mergeable }}" != "true" ]]; then
+            echo "Error: Pull request is not mergeable."
+            exit 1
+          fi
+
           if [[ "${{ github.event.pull_request.merge_commit_sha }}" != "" ]]; then
             echo "Error: Only squash merges are allowed into dev."
             exit 1
